// Configuration for Supabase & Application
window.APP_CONFIG = {
  SUPABASE_URL: "https://lobillrepxkmqsxensnl.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvYmlsbHJlcHhrbXFzeGVuc25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3NjI0NjAsImV4cCI6MjEwNjMzODQ2MH0.LeaHXGniVm5dCnuJtMaq1TKDnMV7jNgF7U9d2EvKLko",
  PAGE_SIZE_OPTIONS: [10, 25, 50, 100, 200],
  DEFAULT_PAGE_SIZE: 25,
  BATCH_SIZE: 100 // for Excel chunked upserting
};

// Column dictionary for mapping and display
window.COLUMN_DEFINITIONS = [
  { key: "id", label: "كود الموظف (ID)", labelEn: "Employee ID", required: true, isKey: true },
  { key: "serial_no", label: "مسلسل (S.)", labelEn: "Serial No" },
  { key: "employee_name", label: "اسم الموظف (EN)", labelEn: "Employee Name", required: true },
  { key: "employee_name_ar", label: "اسم الموظف (عربي)", labelEn: "Employee Name (AR)" },
  { key: "asd", label: "ASD", labelEn: "ASD" },
  { key: "hiring_type", label: "نوع التعيين (Hiring Type)", labelEn: "Hiring Type" },
  { key: "job_post", label: "المسمى الوظيفي (Job Post)", labelEn: "Job Post" },
  { key: "job_title", label: "الوظيفة (Job Title)", labelEn: "Job Title" },
  { key: "managerial_level", label: "المستوى الإداري", labelEn: "Managerial Level" },
  { key: "job_tree", label: "شجرة الوظائف", labelEn: "Job Tree" },
  { key: "company", label: "الشركة (Company)", labelEn: "Company" },
  { key: "company_sector", label: "القطاع (Sector)", labelEn: "Sector" },
  { key: "costed_by_company", label: "التكلفة على (Company)", labelEn: "Costed by Company" },
  { key: "costed_by_sector", label: "التكلفة على (Sector)", labelEn: "Costed by Sector" },
  { key: "locations", label: "الموقع (Location)", labelEn: "Location" },
  { key: "sub_location", label: "الموقع الفرعي", labelEn: "Sub-Location" },
  { key: "division", label: "القطاع / الإدارة العليا", labelEn: "Division" },
  { key: "department", label: "الإدارة (Department)", labelEn: "Department" },
  { key: "sub_department", label: "القسم الفرعي", labelEn: "Sub-Department" },
  { key: "qalaa_department", label: "إدارة القلعة", labelEn: "Qalaa Department" },
  { key: "qalaa_group_functions", label: "وظائف مجموعة القلعة", labelEn: "Qalaa Group Functions" },
  { key: "skilled_unskilled", label: "المهارة (Skilled / Unskilled)", labelEn: "Skilled/Unskilled" },
  { key: "company_level", label: "مستوى الشركة", labelEn: "Company Level" },
  { key: "taqa_level_grade", label: "درجة طاقة (TAQA Grade)", labelEn: "TAQA Level (Grade)" },
  { key: "qalaa_job_group", label: "مجموعة القلعة الوظيفية", labelEn: "Qalaa Job Group" },
  { key: "start_date", label: "تاريخ التعيين", labelEn: "Start Date" },
  { key: "yoe", label: "سنوات الخبرة (YOE)", labelEn: "Years of Experience" },
  { key: "resignation_date", label: "تاريخ الاستقالة", labelEn: "Resignation Date" },
  { key: "gender", label: "النوع (Gender)", labelEn: "Gender" },
  { key: "employment_type", label: "نوع التوظيف", labelEn: "Employment Type" },
  { key: "type_of_contract", label: "نوع العقد", labelEn: "Type of Contract" },
  { key: "birth_date", label: "تاريخ الميلاد", labelEn: "Birth Date" },
  { key: "birth_month", label: "شهر الميلاد", labelEn: "Birth Month" },
  { key: "age", label: "السن (Age)", labelEn: "Age" },
  { key: "national_id", label: "الرقم القومي (National ID)", labelEn: "National ID" },
  { key: "mobile_numbers", label: "رقم الموبايل", labelEn: "Mobile" },
  { key: "insurance_number", label: "الرقم التأميني", labelEn: "Insurance No" },
  { key: "bank_name", label: "اسم البنك", labelEn: "Bank Name" },
  { key: "status", label: "الحالة (Status)", labelEn: "Status" },
  { key: "account_numbers", label: "رقم الحساب البنكي", labelEn: "Bank Account No" },
  { key: "floor", label: "الدور", labelEn: "Floor" },
  { key: "telephone_extension", label: "الداخلي (Extension)", labelEn: "Tel Extension" },
  { key: "email", label: "البريد الإلكتروني", labelEn: "Email" },
  { key: "manager", label: "المدير المباشر", labelEn: "Direct Manager" }
];
